// --- MECHSUITS BANNER (YAML) ---
// mechsuit:
//   codename: "GAMEASSIST_BUILD"
//   project_version: "v0.1.0"
//   purpose: "Bundle authored TypeScript into browser ESM under dist/ without leaking Node APIs."
//   order: ["validate", "bundle", "report"]
//   applicability:
//     runtime: "node_tooling"
//     artifact: "source"
//     host_contracts: ["esbuild", "Node.js fs"]
//   data_class: "Internal"
//   ai_data: "none"
//   refusals:
//     - "Never hand-edit generated dist/ output."
//     - "Never bundle Node built-ins into the Foundry client."
//   observability:
//     mode: "local_diagnostics"
//     logs: "bounded build status on stdout"
//     metrics: []
//     spans: []
//   compatibility:
//     node: { minimum: "20" }
//   policy:
//     notes_ref: "[GAMEASSIST_BUILD:POLICY]"
//   variances: []
//   canonical_tree: |
//     [GAMEASSIST_BUILD]/
//     |-- [GAMEASSIST_BUILD:POLICY]
//     `-- [GAMEASSIST_BUILD:BUNDLE]
// --- prose banner ---
// This Node build script turns src/main.ts into dist/gameassist.mjs. It refuses
// to treat dist/ as source and refuses to include Node built-ins in the client.

import * as esbuild from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ============================================================================
// [GAMEASSIST_BUILD:POLICY] BEGIN
// Section Title: Build inputs, outputs, and refusals
// -----------------------------------------------------------------------------
// mechsuit_section: {
//   codename: "GAMEASSIST_BUILD",
//   area: "POLICY",
//   title: "Build policy",
//   guarantees: ["One browser ESM bundle from src/main.ts to dist/gameassist.mjs."],
//   provides: ["POLICY"],
//   last_updated_version: "v0.1.0",
//   lifecycle: "active"
// }
// -----------------------------------------------------------------------------
// Narrative
// esbuild is the only emitter. TypeScript remains a typecheck, not a second
// emit path. The generated banner tells maintainers not to edit dist/.
// -----------------------------------------------------------------------------
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

const POLICY = {
  entry: path.join(root, "src", "main.ts"),
  outfile: path.join(root, "dist", "gameassist.mjs"),
  target: "es2022",
  banner: "/* GENERATED by scripts/build.mjs from src/main.ts. Do not edit. See __mechsuit__/build-output.md. */\n"
};
// --- Notes & Comments ---
// Changed (v0.1.0): lock the first esbuild emit path and generated-file notice.
// Decision log:
//   CHOICE: esbuild - ALT: Vite or tsc multi-file emit; REJECTED: extra
//   surface area and a more fragile Foundry module graph.
// [GAMEASSIST_BUILD:POLICY] END
// ============================================================================

// ============================================================================
// [GAMEASSIST_BUILD:BUNDLE] BEGIN
// Section Title: Bundle src/main.ts for Foundry
// -----------------------------------------------------------------------------
// mechsuit_section: {
//   codename: "GAMEASSIST_BUILD",
//   area: "BUNDLE",
//   title: "esbuild bundle",
//   guarantees: ["Writes browser ESM to dist/ or exits non-zero."],
//   depends_on: ["[GAMEASSIST_BUILD:POLICY]"],
//   seams: ["esbuild.build", "npm run build"],
//   last_updated_version: "v0.1.0",
//   lifecycle: "active"
// }
// -----------------------------------------------------------------------------
// Narrative
// Validate the entry path by letting esbuild fail if it is missing. platform
// browser prevents Node built-ins from resolving. minify stays off so the
// first shell remains readable during live debugging.
// -----------------------------------------------------------------------------
/**
 * Bundles GameAssist client source into dist/gameassist.mjs.
 *
 * @returns {Promise<void>} Resolves after a successful emit.
 * @throws {Error} When esbuild reports a build failure.
 *
 * Side effects: creates dist/ and writes generated JavaScript plus a source map.
 */
async function bundle() {
  await mkdir(path.dirname(POLICY.outfile), { recursive: true });
  await esbuild.build({
    absWorkingDir: root,
    entryPoints: [POLICY.entry],
    outfile: POLICY.outfile,
    bundle: true,
    format: "esm",
    platform: "browser",
    target: POLICY.target,
    sourcemap: true,
    minify: false,
    logLevel: "info",
    banner: { js: POLICY.banner }
  });
  await writeFile(
    path.join(root, "dist", "GENERATED.md"),
    "# Generated output\n\nDo not edit files in dist/. Rebuild with `npm run build`.\n",
    "utf8"
  );
}

bundle().catch((error) => {
  console.error("[GAMEASSIST_BUILD] bundle failed");
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
// --- Notes & Comments ---
// Changed (v0.1.0): add the foundation esbuild client bundle.
// [GAMEASSIST_BUILD:BUNDLE] END
// ============================================================================
